#ifndef STATUS_SCREEN_CONSTANTS_H
#define STATUS_SCREEN_CONSTANTS_H

enum StatusScreenSection {
    STATUS_SECTION_BEAM,
    STATUS_SECTION_MISSILE,
    STATUS_SECTION_BOMB,
    STATUS_SECTION_SUIT,
    STATUS_SECTION_MISC,
    STATUS_SECTION_ENERGY_CURRENT,
    STATUS_SECTION_ENERGY_MAX,
    STATUS_SECTION_MISSILES_CURRENT,
    STATUS_SECTION_MISSILES_MAX,
    STATUS_SECTION_POWER_BOMBS_CURRENT,
    STATUS_SECTION_POWER_BOMBS_MAX
};

#endif /* STATUS_SCREEN_CONSTANTS_H */
