#ifndef PAUSE_DEBUG_CONSTANTS_H
#define PAUSE_DEBUG_CONSTANTS_H

#include "types.h"

#define PAUSE_DEBUG_TILE_SIZE (QUARTER_BLOCK_SIZE / 2)

enum PauseDebugSection {
    PAUSE_DEBUG_SECTION_BEAM,
    PAUSE_DEBUG_SECTION_MISSILE,
    PAUSE_DEBUG_SECTION_BOMB,
    PAUSE_DEBUG_SECTION_SUIT,
    PAUSE_DEBUG_SECTION_MISC,
    PAUSE_DEBUG_SECTION_ENERGY_CURRENT,
    PAUSE_DEBUG_SECTION_ENERGY_MAX,
    PAUSE_DEBUG_SECTION_SUPPLY,
    PAUSE_DEBUG_SECTION_MISSILE_CURRENT,
    PAUSE_DEBUG_SECTION_MISSILE_MAX,
    PAUSE_DEBUG_SECTION_POWER_BOMB_CURRENT,
    PAUSE_DEBUG_SECTION_POWER_BOMB_MAX,
    PAUSE_DEBUG_SECTION_ABILITY_COUNT,
    PAUSE_DEBUG_SECTION_SECURITY,
    PAUSE_DEBUG_SECTION_MAP,
    PAUSE_DEBUG_SECTION_EVENT,
    PAUSE_DEBUG_SECTION_SOUND_EVENT,
    PAUSE_DEBUG_SECTION_IN_GAME_TIME,
    PAUSE_DEBUG_SECTION_QUICK_SAVE,

    PAUSE_DEBUG_SECTION_END,

    PAUSE_DEBUG_SECTION_ALL = UCHAR_MAX
};

enum PauseDebugEditFlag {
    PAUSE_DEBUG_EDIT_NONE,
    PAUSE_DEBUG_EDIT_REDRAW_SECTION,
    PAUSE_DEBUG_EDIT_REDRAW_NUMBERED_SECTION,
    PAUSE_DEBUG_EDIT_REDRAW_ALL,
};

enum PauseDebugAmmoType {
    PAUSE_DEBUG_AMMO_TYPE_HEALTH,
    PAUSE_DEBUG_AMMO_TYPE_MISSILES,
    PAUSE_DEBUG_AMMO_TYPE_POWER_BOMBS,
};

#endif /* PAUSE_DEBUG_CONSTANTS_H */
